[package]
name = "transaction-processor"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = { version = "1.3" }
rust_decimal = { version = "1.35" }
serde = { version = "1.0", features = ["derive"] }
thiserror = { version = "1.0" }
